services:
  # image project
  dotnet:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dotNet8
    tty: true
    ports:
      - "5000:5000"
      - "5001:5001"
    command: dotnet watch run --urls http://0.0.0.0:5000
    volumes:
      - .:/app
    networks:
      - dotnetwork

  #db mssql
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    user: root
    tty: true
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - dotnetwork

networks:
  dotnetwork:
    driver: bridge